import { show } from './show';
import { alert } from "./alert";
import { confirm } from "./confirm";
import OriginDialog from './dialog';
import "./index.css";
var Dialog = OriginDialog;
Dialog.show = show;
Dialog.alert = alert;
Dialog.confirm = confirm;
export default Dialog;